### ISSUE TITLE
KeyError-249

### ISSUE THREAD

**Issue by Ujwal2910** [chainer/chainerrl#566]
I have been running a3c from chainer but have been getting the following error-

```
Traceback (most recent call last):
  File "/home/ujwal/PycharmProjects/Drone/trainer_a3c_mulit.py", line 256, in <module>
    main()
  File "/home/ujwal/PycharmProjects/Drone/trainer_a3c_mulit.py", line 246, in main
    save_best_so_far_agent=True,logger=None)
  File "/home/ujwal/anaconda3/lib/python3.7/site-packages/chainerrl/experiments/train_agent.py", line 163, in train_agent_with_evaluation
    logger=logger)
  File "/home/ujwal/anaconda3/lib/python3.7/site-packages/chainerrl/experiments/train_agent.py", line 65, in train_agent
    agent.stop_episode_and_train(obs, r, done=done)
  File "/home/ujwal/anaconda3/lib/python3.7/site-packages/chainerrl/agents/a3c.py", line 295, in stop_episode_and_train
    self.update(statevar)
  File "/home/ujwal/anaconda3/lib/python3.7/site-packages/chainerrl/agents/a3c.py", line 181, in update
    v = self.past_values[i]
KeyError: 249
```
Help would be appreciated.

**Comment by Ujwal2910** [comment]
removed checkpoint frequency in the training code snippet and it started working fine.
